version: '3'

services:

  sane-flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: neocampus/sane-flask-api:1.0
    restart: unless-stopped
    container_name: sane-flask-api
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - "5443:5443"
    environment:
      - TZ=Europe/Paris

